final Map<int, String> licencasArbitros = {
  18: 'Jorge Manuel de Oliveira Marques',
  86: 'Juan Carlos Hernando Alijas',
  97: 'Bruno José Lopes Correia de Sá',
  121: 'Hugo Blanco Marques da Silva',
  145: 'Bruno Miguel da Silva Lourenço Velha',
  146: 'Olga Cristina Bastos Santos',
  147: 'Paulo Jorge Moreira Almeida',
  217: 'Jorge André Soares Braga',
  267: 'António Manuel de Castro Martins Pereira',
  275: 'Eduardo Brito',
  280: 'César José Samina Fernandes',
  558: 'Rodrigo Seixas Lopes',
  645: 'Gonçalo Daniel Pires de Almeida',
  681: 'Flávio Rafael Barros',
  704: 'Renato Filipe Preto Ramos dos Reis',
  705: 'Ruben Alexandre Almeida Vieira',
  765: 'João Marçal',
  971: 'Fábio Daniel Almeida Dias',
  1072: 'Diogo Emanuel Silva',
  5735: 'Joana Raquel Gomes Costa',
  14302: 'Tiago Rocha',
  16706: 'Rodrigo Duque',
  16828: 'Diogo Pereira Oliveira',
  17604: 'Jeatsaret Travieso',
  18538: 'Lord Caballero',
  18540: 'Rafael Bastos Ribeiro',
  18544: 'Bárbara Carolina Duarte Barreiro',
  18594: 'Dinis Margalhau Fidalgo',
  18602: 'Rodrigo Sá Costa',
  18761: 'Dan Borek',
  18758: 'Anaya',
  226: 'Ana Margarida Forte de Pinho Costa',
  19003: 'Daniel António Neves Coelho Filipe',
  19110: 'Daniel Kovalchuck',
  19005: 'Diogo da Costa Dias Batista',
  19083: 'Gabriel Pinheiro Soares',
  19132: 'Guilherme Migueis',
  19111: 'Guilherme Alves Correia de Oliveira',
  19006: 'João Miguel Alves Pereira',
  19008: 'Leonardo Oliveira Carvalho',
  19017: 'Rafaela Almeida Dias',
  19086: 'Renata Martinho Brochado Miguéis',
  19087: 'Riquelme Rafael da Silva Sissé',
  19020: 'Rodrigo Rocha Mendes',
  19026: 'Stela de Almeida Direitinho',
  19115: 'Tomás Henrique Costa Simões dos Ramos Pereira',
  19025: 'Vasco Manuel Pereira Ferreira',
  18909: 'Shelson Sanjoaneira',
};

final Map<int, String> licencasOficiais = {
    1: 'Joaquim dos Santos Silva',
    8: 'Luis Carlos Conceição Aires Santiago',
    16: 'Aldina Manuela Russo Gonçalves Costa',
    19: 'Dulce Paula Migueis Junqueiro',
    25: 'Olga Matos das Neves Sucena',
    36: 'Nuno Miguel Lopes Jorge Silva',
    37: 'Jorge Manuel Barbosa da Costa',
    148: 'Teresa Mª Filipe Bernardo Nascimento',
    149: 'Teresa Marta Mouro Oliveira',
    150: 'Telmo André Almeida Dias',
    186: 'Elmano Manuel Simões Martins Pereira',
    219: 'Sara Sofia Castro Martins Pereira',
    268: 'Pedro Filipe Ferreira Oliveira',
    269: 'Paula Alexandra Fern Mota Veiga',
    282: 'Ivo José Coentro Ruela Vieira',
    369: 'Marisa Campos Gonçalves',
    376: 'Fernando da Silva Araújo',
    384: 'Cátia Soares Azevedo',
    559: 'Pedro Miguel Silva Caseiro',
    706: 'Beatriz Batista Velha',
    711: 'Rita Azevedo Plaza',
    760: 'Débora Patricia Ruas Agostinho',
    993: 'José França',
    1074: 'Rui Filipe Catelas Pinto',
    5730: 'Ana Rita Nogueira dos Santos',
    16360: 'José Pedro da Rocha Fernandes',
    16833: 'Diogo Jorge Oliveira Peralta',
    17167: 'Brenda Neves',
    17169: 'Gabriela Neves Silva',
    17864: 'Beatriz Junqueiro e Silva',
    17873: 'Bruna Batista Velha',
    17882: 'Rodrigo Lopes Oliveira',
    17883: 'Bárbara Cunha',
    18532: 'Ana Maria Silva e Cunha',
    18533: 'Ana Claúdia Vasconcelos Pereira',
    18533: 'Ana Claudia Vasconcelos Pereira',
    18536: 'Gonçalo Seabra Ribeiro',
    18537: 'João Francisco Simões de Freitas',
    18596: 'Mariana Cravo Garcia',
    18597: 'Miguel Leite Sales de Brito',
    18598: 'Paula Idalina Garcia Duarte',
    18648: 'Maria Gabriel dos Santos Teixeira',
    18650: 'Susana de Almeida Lopes Ferreira',
    18656: 'Adriana Neves',
    17048: 'António Lima',
    19119: 'Afonso Santiago Bandeira monteiro',
    18998: 'Ana Lúcia Ruela da Silva',
    19080: 'Andrea Paula Jesus Patela',
    18999: 'Angelica Pereira de Almeida',
    19000: 'Beatriz Filipa de Jesus Sousa',
    19001: 'Bernardo Carvalheira Maia Campos',
    19002: 'Bruno Miguel Tavares Marques Fernandes',
    19109: 'Bruno Duarte Mairos Ferreira',
    19081: 'Carolina Sofia Santos Sousa',
    19004: 'Daniela Vasques Fontes Pinto',
    19118: 'David Valente',
    19082: 'Fábio André Pereira Cruz',
    19084: 'José Manuel Oliveira Leite',
    19010: 'Maria do Céu Pereira Branco',
    19116: 'Maria João Fernandes Pinho',
    19117: 'Mariana Filipa Bandeira',
    19012: 'Mariana Silva Bastos',
    19085: 'Nadine Filipa Alves Rola',
    19013: 'Neide Denise Ferreira Bernardo',
    19112: 'Noemy Isabel Ferreira Bernardo',
    19015: 'Nuno Filipe Morgado Coelho Henriques',
    19016: 'Nuno Maria Santos Filipe Seabra',
    19122: 'Raquel Catarina Martins Silva ',
    19018: 'Ricardo André Martins Mendes',
    19019: 'Rita de Azevedo Lopes',
    19021: 'Samuel Caetano Augusto Martins Pereira',
    19022: 'Sandra Maria Ferreira Vieira',
    19023: 'Sofia Leite Sales de Brito',
    19024: 'Soraia Patricia Gomes Salsa',
    17172: 'Tiago Azevedo Plaza',
    18049: 'Gabriela Reis',
};

final Set<int> estagiarios = {
  // Nenhum por agora — ativar no futuro se necessário
  19003, 19110, 19005, 19083,
};

/// Junta os dois mapas num só com `String` como chave
final Map<String, String> licencasENomes = {
  ...licencasArbitros.map((k, v) => MapEntry(k.toString(), v)),
  ...licencasOficiais.map((k, v) => MapEntry(k.toString(), v)),
};

/// Função auxiliar para uso geral
String obterNomePorLicenca(String input) {
  final numero = int.tryParse(input);
  if (numero == null) return '❌ Licença inválida';
  return licencasArbitros[numero] ?? licencasOficiais[numero] ?? '❌ Licença não encontrada';
}